pipeline {
  agent any
  environment {
        CREDENTIALS = credentials('dockerhub')
  }
  stages {
    stage('Checkout') {
            steps {
                git url: 'https://github.com/omareldemerdash/Depi_project.git', branch: 'main'
            }
        }
    stage('Terraform apply') {
            steps {
                // Initialize Terraform, show plan, and apply it in a single command
                sh '''
                    terraform init
                    terraform plan -out=tfplan
                    terraform apply -auto-approve tfplan
                '''
            }
        }
    stage('build') {
     	    steps {
        	sh '''
        	    docker build -t omareldemerdash28/inks-db:latest -f Dockerfile.db  .;
		    docker build -t omareldemerdash28/inks-app:latest -f Dockerfile.app .;
        	    echo $CREDENTIALS_PSW | docker login -u $CREDENTIALS_USR --password-stdin;
        	    docker push omareldemerdash28/inks-db:latest
        	    echo $CREDENTIALS_PSW | docker login -u $CREDENTIALS_USR --password-stdin;
        	    docker push omareldemerdash28/inks-app:latest
        	'''

      }
    }

  }
}
