pipeline {
  agent any
  environment {
        CREDENTIALS = credentials('dockerhub')
        AWS_DEFAULT_REGION = 'us-east-1'
  }
  parameters {
        string(name: 'TF_WORKSPACE', defaultValue: 'dev', description: 'Terraform Workspace')
    }
  stages {
    stage('Checkout') {
            steps {
                git url: 'https://github.com/omareldemerdash/Depi_project.git', branch: 'main'
            }
        }
    stage('Terraform apply') {
            steps {
                // Initialize Terraform, show plan, and apply it in a single command
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                        terraform init
                        terraform plan
			terraform workspace list
                   	terraform workspace select ${TF_WORKSPACE} || terraform workspace new ${TF_WORKSPACE} 
                        terraform apply -auto-approve 
                    ''' 
                }
                
            }
        }
    stage('build') {
     	    steps {
        	sh '''
        	    docker build -t omareldemerdash28/inks-db:latest -f Dockerfile.db  .;
		    docker build -t omareldemerdash28/inks-app:latest -f Dockerfile.app .;
        	    echo $CREDENTIALS_PSW | docker login -u $CREDENTIALS_USR --password-stdin;
        	    docker push omareldemerdash28/inks-db:latest
        	    echo $CREDENTIALS_PSW | docker login -u $CREDENTIALS_USR --password-stdin;
        	    docker push omareldemerdash28/inks-app:latest
        	'''

      }
    }

  }
}
